version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb

  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://myuser:admin@db:5432/mydb
    depends_on:
      - db
